[package]

name = "multiboot"
version = "0.0.1"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

description = "Library to access multiboot structures."
homepage = "https://github.com/gz/rust-multiboot"
repository = "git@github.com:gz/rust-multiboot.git"

readme = "README.md"
keywords = ["multiboot", "kernel", "os", "bootloader", "x86"]
license = "MIT License"
